#include "Entities/Player.h"
#include "Entities/Tombstone.h"
#include "Utils/Constants.h"
#include "World/Collision.h"
#include "World/Level.h"
#include <algorithm>
#include <memory>
namespace { float approach(float value,float target,float step){return value<target?std::min(value+step,target):std::max(value-step,target);} }
const std::vector<Player::Profile>& Player::profiles(){static const std::vector<Profile> p={{"Sky","High jump","Jumps much higher.",{102,183,232},1,1.22f,1,1,Constants::PLAYER_MAX_HEALTH,false},{"Rush","Fast move","Runs faster.",{105,214,146},1.26f,1,1,1,Constants::PLAYER_MAX_HEALTH,false},{"Guard","First hit guard","Blocks first hit.",{238,210,96},1,1,1,1,Constants::PLAYER_MAX_HEALTH,true},{"Titan","Tank health","More health.",{227,164,85},.92f,.95f,1,1,Constants::PLAYER_MAX_HEALTH+3,false},{"Feather","Slow fall","Falls slowly.",{194,146,232},1,1,.72f,.66f,Constants::PLAYER_MAX_HEALTH,false},{"Legend","All traits","All traits.",{245,111,211},1.26f,1.22f,.72f,.66f,Constants::PLAYER_MAX_HEALTH+3,true}};return p;}
Player::Player(int id,sf::Vector2f pos,Profile p):Character(pos,{26,42},p.maxHealth),color(p.color),lastSafePosition(pos),id(id),spawn(pos),firstHitGuardAvailable(p.blocksFirstHit),profile(std::move(p)){inventory.block=Constants::START_BLOCK_COUNT;}
void Player::update(float dt,const InputState& input,Level& level){attackTimer=std::max(0.f,attackTimer-dt);dodgeTimer=std::max(0.f,dodgeTimer-dt);dodgeCooldownTimer=std::max(0.f,dodgeCooldownTimer-dt);if(respawnTimer>0){if((respawnTimer-=dt)<=0){position=spawn;velocity={};health=maxHealth;hunger=50;firstHitGuardAvailable=profile.blocksFirstHit;}return;}int move=int(input.moveRight)-int(input.moveLeft);velocity.x=approach(velocity.x,move*Constants::PLAYER_SPEED*profile.speedMultiplier,(onGround?Constants::PLAYER_GROUND_ACCELERATION:Constants::PLAYER_AIR_ACCELERATION)*dt);if(move)facingDirection=move;coyoteTimer=onGround?Constants::PLAYER_COYOTE_TIME:std::max(0.f,coyoteTimer-dt);if(input.jump&&coyoteTimer>0){velocity.y=Constants::PLAYER_JUMP_SPEED*profile.jumpMultiplier;coyoteTimer=0;}if(input.attack)attackTimer=.18f;if(input.dodge&&dodgeCooldownTimer<=0){dodgeTimer=Constants::PLAYER_DODGE_DURATION;dodgeCooldownTimer=Constants::PLAYER_DODGE_COOLDOWN;}if(input.placeBlock)level.tryPlaceBlock(*this);if(input.throwItem)level.throwItem(*this);velocity.y=std::min(Constants::MAX_FALL_SPEED*profile.maxFallMultiplier,velocity.y+Constants::GRAVITY*profile.gravityMultiplier*dt);velocity*=dt;Collision::resolveTileCollision(*this,level.getTileMap());velocity/=dt;if(onGround)lastSafePosition=position;if(position.y>level.getTileMap().heightPixels()+260)die(level,true);}
void Player::draw(sf::RenderWindow& w,sf::Vector2f camera)const{if(isRespawning())return;sf::RectangleShape body(size);body.setPosition(position-camera);body.setFillColor(sf::Color(color.r,color.g,color.b,isDodging()?110:255));w.draw(body);if(isAttacking()){const auto box=attackBox();sf::RectangleShape slash(box.size);slash.setPosition(box.position-camera);slash.setFillColor({255,229,128,150});w.draw(slash);}}void Player::takeDamage(int d,float knockback){if(isRespawning())return;if(firstHitGuardAvailable){firstHitGuardAvailable=false;return;}Character::takeDamage(d,knockback);}void Player::heal(int a){health=std::min(maxHealth,health+a);}void Player::restoreHunger(int a){hunger=std::min<float>(Constants::PLAYER_MAX_HUNGER,hunger+a);}void Player::die(Level& l,bool fell){if(isRespawning())return;auto stored=inventory.takeAll();if(!stored.empty())l.addTombstone(std::make_unique<Tombstone>(fell?lastSafePosition:position,stored,id));health=0;respawnTimer=2;diedBefore=true;recoveredTombstone=false;}bool Player::isRespawning()const{return respawnTimer>0;}bool Player::isDodging()const{return dodgeTimer>0&&!isRespawning();}bool Player::hasCollectedOwnTombstone()const{return recoveredTombstone;}sf::FloatRect Player::attackBox()const{return {{facingDirection>0?position.x+size.x-2:position.x-34,position.y+8},{36,28}};}bool Player::isAttacking()const{return attackTimer>0&&!isRespawning();}int Player::getId()const{return id;}int Player::getFacingDirection()const{return facingDirection;}float Player::getHunger()const{return hunger;}float Player::getRespawnTimer()const{return respawnTimer;}const Player::Profile& Player::getProfile()const{return profile;}sf::Vector2f Player::getSpawn()const{return spawn;}void Player::setSpawn(sf::Vector2f p){spawn=p;lastSafePosition=p;}void Player::markTombstoneRecovered(){recoveredTombstone=true;}bool Player::hasDiedBefore()const{return diedBefore;}
